
FLAG=-D SRC_MAIN

#$@:
#	g++ $@.cpp $(FLAG) -o $@.out




test-1:
	g++ $@.cpp $(FLAG) -o $@.out

test-class-1:
	g++ $@.cpp $(FLAG) -o $@.out

test-class-2:
	g++ $@.cpp $(FLAG) -o $@.out

test-type-1:
	g++ $@.cpp $(FLAG) -o $@.out

smart-pointer:
	g++ $@-test.cpp $(FLAG) -o $@.out

clean:
	rm *.out

